export const PROGRAMS_DATA = [
  {
    id: 1,
    name: "Bachelor of Business Administration",
    university: 1,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 75000,
    language: "English",
    intake: ["January", "September"],
    scholarship: true,
    description:
      "A comprehensive business program covering management, marketing, finance, and entrepreneurship with industry internships.",
    entryRequirements: [
      "High school certificate with minimum 80%",
      "IELTS 6.0 or equivalent",
      "Personal statement",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 2,
    name: "Master of Business Administration",
    university: 1,
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 120000,
    language: "English",
    intake: ["January", "May", "September"],
    scholarship: true,
    description:
      "An advanced business degree focusing on leadership, strategic management, and global business practices.",
    entryRequirements: [
      "Bachelor's degree with minimum GPA 3.0",
      "IELTS 6.5 or equivalent",
      "2 years work experience",
      "GMAT score of 550+",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "GMAT score report",
      "Two recommendation letters",
      "Copy of passport",
    ],
  },
  {
    id: 3,
    name: "Bachelor of Science in Computer Science",
    university: 1,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 85000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A program covering programming, algorithms, artificial intelligence, and software development with practical projects.",
    entryRequirements: [
      "High school certificate with minimum 85%",
      "Strong mathematics background",
      "IELTS 6.0 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 4,
    name: "Bachelor of Architecture",
    university: 2,
    degreeLevel: "Bachelor",
    duration: "5 years",
    tuitionFee: 95000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A professional degree program preparing students for careers in architecture with studio-based learning and internships.",
    entryRequirements: [
      "High school certificate with minimum 85%",
      "Portfolio of creative work",
      "IELTS 6.5 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "Portfolio",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 5,
    name: "Master of Science in Engineering Systems Management",
    university: 2,
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 130000,
    language: "English",
    intake: ["January", "September"],
    scholarship: false,
    description:
      "An interdisciplinary program combining engineering, systems thinking, and management principles for technical leadership roles.",
    entryRequirements: [
      "Bachelor's degree in engineering or related field with minimum GPA 3.0",
      "IELTS 6.5 or equivalent",
      "Statement of purpose",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Two recommendation letters",
      "Statement of purpose",
      "Copy of passport",
    ],
  },
  {
    id: 6,
    name: "Bachelor of Science in Communication and Media Sciences",
    university: 3,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 70000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A program focusing on digital media, strategic communication, and media production with industry partnerships.",
    entryRequirements: [
      "High school certificate with minimum 75%",
      "IELTS 6.0 or equivalent",
      "Personal interview",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 7,
    name: "Master of Education",
    university: 3,
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 90000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "An advanced program for educators focusing on educational leadership, curriculum development, and teaching methodologies.",
    entryRequirements: [
      "Bachelor's degree with minimum GPA 3.0",
      "IELTS 6.5 or equivalent",
      "2 years teaching experience",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Two recommendation letters",
      "Statement of purpose",
      "Copy of passport",
    ],
  },
  {
    id: 8,
    name: "PhD in Business Administration",
    university: 1,
    degreeLevel: "PhD",
    duration: "4 years",
    tuitionFee: 180000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A doctoral program developing advanced research skills in business disciplines with opportunities for academic publication.",
    entryRequirements: [
      "Master's degree with minimum GPA 3.5",
      "IELTS 7.0 or equivalent",
      "Research proposal",
      "Academic writing sample",
    ],

    documentsNeeded: [
      "Master's degree certificate and transcripts",
      "Bachelor's degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Research proposal",
      "Writing sample",
      "Three recommendation letters",
      "Copy of passport",
    ],
  },
  {
    id: 9,
    name: "Bachelor of Science in Finance",
    university: 2,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 80000,
    language: "English",
    intake: ["January", "September"],
    scholarship: true,
    description:
      "A specialized program covering financial markets, investment analysis, corporate finance, and financial planning.",
    entryRequirements: [
      "High school certificate with minimum 80%",
      "Strong mathematics background",
      "IELTS 6.0 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 10,
    name: "Bachelor of Arts in International Studies",
    university: 3,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 65000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A multidisciplinary program exploring global politics, economics, culture, and international relations with study abroad opportunities.",
    entryRequirements: [
      "High school certificate with minimum 75%",
      "IELTS 6.0 or equivalent",
      "Personal statement",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
      "Personal statement",
    ],
  },
  {
    id: 11,
    name: "Master of Arts in Diplomacy and International Affairs",
    university: 3,
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 95000,
    language: "English",
    intake: ["September"],
    scholarship: false,
    description:
      "An advanced program preparing students for careers in diplomacy, international organizations, and global policy analysis.",
    entryRequirements: [
      "Bachelor's degree with minimum GPA 3.0",
      "IELTS 6.5 or equivalent",
      "Statement of purpose",
      "Writing sample",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Two recommendation letters",
      "Statement of purpose",
      "Writing sample",
      "Copy of passport",
    ],
  },
  {
    id: 12,
    name: "Bachelor of Fine Arts",
    university: 2,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 75000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A creative program developing skills in visual arts, design, and multimedia with exhibition opportunities and industry projects.",
    entryRequirements: [
      "High school certificate with minimum 75%",
      "Portfolio of creative work",
      "IELTS 6.0 or equivalent",
      "Interview",
    ],

    documentsNeeded: [
      "High school transcripts",
      "Portfolio",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 13,
    name: "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
    university: 4,
    degreeLevel: "Bachelor",
    duration: "6 years",
    tuitionFee: 150000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A comprehensive medical program with clinical rotations in affiliated hospitals preparing students for medical practice.",
    entryRequirements: [
      "High school certificate with minimum 90%",
      "Strong science background (Biology, Chemistry, Physics)",
      "IELTS 6.5 or equivalent",
      "Entrance exam",
      "Interview",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
      "Medical fitness certificate",
    ],
  },
  {
    id: 14,
    name: "Master of Public Health",
    university: 4,
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 100000,
    language: "English",
    intake: ["January", "September"],
    scholarship: true,
    description:
      "A program focusing on epidemiology, health policy, environmental health, and healthcare management with field projects.",
    entryRequirements: [
      "Bachelor's degree in health sciences or related field with minimum GPA 3.0",
      "IELTS 6.5 or equivalent",
      "Statement of purpose",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Two recommendation letters",
      "Statement of purpose",
      "Copy of passport",
    ],
  },
  {
    id: 15,
    name: "Bachelor of Science in Environmental Sciences",
    university: 4,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 70000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A program studying ecosystems, conservation, sustainability, and environmental management with field trips and research projects.",
    entryRequirements: [
      "High school certificate with minimum 80%",
      "Strong science background",
      "IELTS 6.0 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 16,
    name: "PhD in Molecular Medicine",
    university: 4,
    degreeLevel: "PhD",
    duration: "4 years",
    tuitionFee: 200000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A research-intensive doctoral program focusing on molecular mechanisms of disease, drug discovery, and personalized medicine.",
    entryRequirements: [
      "Master's degree in life sciences or related field with minimum GPA 3.5",
      "IELTS 7.0 or equivalent",
      "Research proposal",
      "Interview",
    ],

    documentsNeeded: [
      "Master's degree certificate and transcripts",
      "Bachelor's degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Research proposal",
      "Three recommendation letters",
      "Copy of passport",
    ],
  },
  {
    id: 17,
    name: "Bachelor of Science in Aerospace Engineering",
    university: 5,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 90000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A specialized engineering program covering aircraft design, propulsion systems, aerodynamics, and space technology with laboratory work.",
    entryRequirements: [
      "High school certificate with minimum 85%",
      "Strong mathematics and physics background",
      "IELTS 6.0 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 18,
    name: "Master of Science in Artificial Intelligence",
    university: 5,
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 120000,
    language: "English",
    intake: ["January", "September"],
    scholarship: true,
    description:
      "An advanced program exploring machine learning, neural networks, computer vision, and AI applications with industry projects.",
    entryRequirements: [
      "Bachelor's degree in computer science, engineering or related field with minimum GPA 3.0",
      "Programming experience",
      "IELTS 6.5 or equivalent",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Two recommendation letters",
      "Statement of purpose",
      "Copy of passport",
    ],
  },
  {
    id: 19,
    name: "Bachelor of Science in Petroleum Engineering",
    university: 5,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 95000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A program focusing on oil and gas exploration, drilling technologies, reservoir management, and production optimization with industry internships.",
    entryRequirements: [
      "High school certificate with minimum 85%",
      "Strong mathematics and chemistry background",
      "IELTS 6.0 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 20,
    name: "PhD in Robotics and Autonomous Systems",
    university: 5,
    degreeLevel: "PhD",
    duration: "4 years",
    tuitionFee: 180000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A cutting-edge research program developing advanced robotics technologies, autonomous systems, and human-robot interaction.",
    entryRequirements: [
      "Master's degree in engineering, computer science or related field with minimum GPA 3.5",
      "IELTS 7.0 or equivalent",
      "Research proposal",
      "Interview",
    ],

    documentsNeeded: [
      "Master's degree certificate and transcripts",
      "Bachelor's degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Research proposal",
      "Three recommendation letters",
      "Copy of passport",
    ],
  },
  {
    id: 21,
    name: "Bachelor of Science in Cybersecurity",
    university: 6,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 85000,
    language: "English",
    intake: ["January", "September"],
    scholarship: false,
    description:
      "A specialized program covering network security, ethical hacking, digital forensics, and security management with practical labs.",
    entryRequirements: [
      "High school certificate with minimum 80%",
      "IELTS 6.0 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 22,
    name: "Master of Science in Sustainable Energy",
    university: 6,
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 110000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "An interdisciplinary program exploring renewable energy technologies, energy efficiency, sustainability, and policy with research projects.",
    entryRequirements: [
      "Bachelor's degree in engineering, environmental science or related field with minimum GPA 3.0",
      "IELTS 6.5 or equivalent",
      "Statement of purpose",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Two recommendation letters",
      "Statement of purpose",
      "Copy of passport",
    ],
  },
  {
    id: 23,
    name: "Bachelor of Arts in Psychology",
    university: 6,
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 70000,
    language: "English",
    intake: ["September"],
    scholarship: true,
    description:
      "A comprehensive program exploring human behavior, cognitive processes, development, and psychological research methods with practical training.",
    entryRequirements: [
      "High school certificate with minimum 75%",
      "IELTS 6.0 or equivalent",
    ],

    documentsNeeded: [
      "High school transcripts",
      "English proficiency test results",
      "Copy of passport",
      "Passport-sized photographs",
    ],
  },
  {
    id: 24,
    name: "Master of Business Administration (Executive)",
    university: 6,
    degreeLevel: "Master",
    duration: "18 months",
    tuitionFee: 140000,
    language: "English",
    intake: ["January", "September"],
    scholarship: false,
    description:
      "An accelerated MBA program for experienced professionals focusing on leadership, strategy, and organizational transformation with weekend classes.",
    entryRequirements: [
      "Bachelor's degree with minimum GPA 3.0",
      "IELTS 6.5 or equivalent",
      "Minimum 5 years of managerial experience",
      "Interview",
    ],

    documentsNeeded: [
      "Bachelor degree certificate and transcripts",
      "CV/Resume",
      "English proficiency test results",
      "Two recommendation letters",
      "Statement of purpose",
      "Copy of passport",
      "Employer endorsement letter",
    ],
  },
];
