export interface SavedProgram {
  id: number;
  programId: number;
  programName: string;
  university: number;
  universityName: string;
  universityLogo?: string;
  degreeLevel: string;
  duration: string;
  tuitionFee: number;
  intake: string[];
  scholarship: boolean;
  dateAdded: string;
  notes?: string;
  deadlineDate?: string;
}

export const SAVED_PROGRAMS_DATA: SavedProgram[] = [
  {
    id: 1,
    programId: 3,
    programName: "Bachelor of Science in Computer Science",
    university: 1,
    universityName: "University of Dubai",
    universityLogo: "https://picsum.photos/seed/univ1/200/80",
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 85000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "July 1, 2023",
    notes: "Great program with internship opportunities",
    deadlineDate: "August 15, 2023",
  },
  {
    id: 2,
    programId: 18,
    programName: "Master of Science in Artificial Intelligence",
    university: 5,
    universityName: "Khalifa University",
    universityLogo: "https://picsum.photos/seed/univ5/200/80",
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 120000,
    intake: ["January", "September"],
    scholarship: true,
    dateAdded: "June 28, 2023",
    deadlineDate: "October 15, 2023",
  },
  {
    id: 3,
    programId: 4,
    programName: "Bachelor of Architecture",
    university: 2,
    universityName: "American University of Sharjah",
    universityLogo: "https://picsum.photos/seed/univ2/200/80",
    degreeLevel: "Bachelor",
    duration: "5 years",
    tuitionFee: 95000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "June 25, 2023",
    notes: "Need to prepare portfolio",
    deadlineDate: "July 30, 2023",
  },
  {
    id: 4,
    programId: 7,
    programName: "Master of Education",
    university: 3,
    universityName: "Zayed University",
    universityLogo: "https://picsum.photos/seed/univ3/200/80",
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 90000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "July 5, 2023",
    deadlineDate: "August 30, 2023",
  },
  {
    id: 5,
    programId: 13,
    programName: "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
    university: 4,
    universityName: "UAE University",
    universityLogo: "https://picsum.photos/seed/univ4/200/80",
    degreeLevel: "Bachelor",
    duration: "6 years",
    tuitionFee: 150000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "June 30, 2023",
    notes: "Need to prepare for entrance exam",
    deadlineDate: "July 15, 2023",
  },
  {
    id: 6,
    programId: 22,
    programName: "Master of Science in Sustainable Energy",
    university: 6,
    universityName: "Abu Dhabi University",
    universityLogo: "https://picsum.photos/seed/univ6/200/80",
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 110000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "July 3, 2023",
    deadlineDate: "August 20, 2023",
  },
  {
    id: 7,
    programId: 9,
    programName: "Bachelor of Science in Finance",
    university: 2,
    universityName: "American University of Sharjah",
    universityLogo: "https://picsum.photos/seed/univ2/200/80",
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 80000,
    intake: ["January", "September"],
    scholarship: true,
    dateAdded: "July 7, 2023",
    deadlineDate: "September 15, 2023",
  },
  {
    id: 8,
    programId: 11,
    programName: "Master of Arts in Diplomacy and International Affairs",
    university: 3,
    universityName: "Zayed University",
    universityLogo: "https://picsum.photos/seed/univ3/200/80",
    degreeLevel: "Master",
    duration: "2 years",
    tuitionFee: 95000,
    intake: ["September"],
    scholarship: false,
    dateAdded: "July 2, 2023",
    notes: "Need writing sample",
    deadlineDate: "August 10, 2023",
  },
  {
    id: 9,
    programId: 21,
    programName: "Bachelor of Science in Cybersecurity",
    university: 6,
    universityName: "Abu Dhabi University",
    universityLogo: "https://picsum.photos/seed/univ6/200/80",
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 85000,
    intake: ["January", "September"],
    scholarship: false,
    dateAdded: "June 29, 2023",
    deadlineDate: "August 25, 2023",
  },
  {
    id: 10,
    programId: 15,
    programName: "Bachelor of Science in Environmental Sciences",
    university: 4,
    universityName: "UAE University",
    universityLogo: "https://picsum.photos/seed/univ4/200/80",
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 70000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "July 8, 2023",
    deadlineDate: "August 5, 2023",
  },
  {
    id: 11,
    programId: 19,
    programName: "Bachelor of Science in Petroleum Engineering",
    university: 5,
    universityName: "Khalifa University",
    universityLogo: "https://picsum.photos/seed/univ5/200/80",
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 95000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "July 6, 2023",
    notes: "Strong math background required",
    deadlineDate: "August 15, 2023",
  },
  {
    id: 12,
    programId: 23,
    programName: "Bachelor of Arts in Psychology",
    university: 6,
    universityName: "Abu Dhabi University",
    universityLogo: "https://picsum.photos/seed/univ6/200/80",
    degreeLevel: "Bachelor",
    duration: "4 years",
    tuitionFee: 70000,
    intake: ["September"],
    scholarship: true,
    dateAdded: "July 4, 2023",
    deadlineDate: "August 30, 2023",
  },
];
